services:
  app:
    extends:
      file: docker-compose.yml
      service: app
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    command: make dev

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app